### ISSUE TITLE
Setup kubernetes with monitoring

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/fusion-node#1]
https://medium.com/@iruwen/running-a-fusion-node-on-linux-part-1-21d44e73972c

Need to monitor when docker container goes down, get alert via slack (prometheus?) I don't really need graphics/charts, but alerts

Use kubernetes 2 node cluster cannot have any downtime

Need to keep all logs so we can figure out what went wrong, currently the past logs are discarded so I'm not sure what went wrong.

Provision with terraform

**Comment by nutshell113** [comment]
Required steps:
- [ ] Provisioning  k8s with terraform (with 2 nodes)
- [ ] Deploy FSN as k8s deployment
- [ ] Logging with Promtail + Loki
- [ ] Metrics & alert with Prometheus + Alertmanager
- [ ] Metrics visualizing/ Log accessing by Grafana

Some question @webberwang :
- What about log retention ? How long? 
- What about Kubernetes nodes hardware specs ? How many CPU + RAM per a node ?

**Comment by webberwang** [comment]
we’ll use smallest for now, 1 node only actually 

1 month at least

**Comment by nutshell113** [comment]
Working on https://github.com/codelab-ai/fusion-node/pull/2

**Comment by nutshell113** [comment]
Forget this idea.
